Sprint 2/step 2
swtormy/react-burger pull request #5
Opened 2023-11-06 14:01 UTC by swtormy

2023-11-06 15:49 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/2vj2QfqKUN5JFw> - шрифт не подтянулся;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/P7NpnGMCedFdOw>;

- Нужно запретить нажатие кнопки, если пользователь выбрал только ингредиенты (или не выбрал ничего) <https://disk.yandex.com/i/jRxaPR3mS0UIWw>;

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-11-06 15:49 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    const constIng = constructorIngredients?.map(ingredient => ingredient._id);
**Надо исправить:**

В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива.

2023-11-06 15:49 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    order && openModal(order)
**Можно лучше:**

Тут лучше написать условие с `if`, читабельность будет повыше)

2023-11-06 15:49 UTC, ArslanMustafin commented on src/components/burger-constructor/burger/burger.jsx
> +                const currentBuns = constructorIngredients.filter(ingredient => ingredient.type === 'bun');
**Можно лучше:**

тут лучше использовать метод [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).
Тогда не придётся дополнительно использовать цикл ниже.

2023-11-06 15:49 UTC, ArslanMustafin commented on src/components/burger-constructor/burger/burger.jsx
> +                dispatch(addIngredient({ ...item, position: 'bottom' }));
**Можно лучше:**

Может быть просто сделать отдельный экшен для добавления булки, а не вызывать 2 раза существующий с разными параметрами.

2023-11-06 15:49 UTC, ArslanMustafin commented on src/components/burger-constructor/burger/burger.jsx
> +                ingredient.type === 'bun' && ingredient.position === 'top' && (
**Можно лучше:**

условие `ingredient.position === 'top'`  избыточно, т.к. булки у нас одинаковые

2023-11-06 15:49 UTC, ArslanMustafin commented on src/components/burger-constructor/burger/burger.jsx
> +            {constructorIngredients?.map((ingredient) => (
**Можно лучше:**

Лучше изначально разделить булку и ингредиенты:

```js
const { bun, otherIngredients } = {
  bun: ingredients.find(item => item.type === 'bun'),
  otherIngredients: ingredients.filter(item => item.type !== 'bun'),
};
```

А в идеале сделать такую же конструкцию в редьюсере. И сразу получать готовые данные для использования.

2023-11-06 15:49 UTC, ArslanMustafin commented on src/components/burger-constructor/draggable-element/draggable-element.jsx
> +            key={uuidv4()}
**Надо исправить:**

Нужно убрать `key` вы ведь не итерируетесь в цикле.

А также, не рекомендую использовать `uuid` таким оброазом. `uuidv4()` генерирует новый случайный UUID при каждом вызове. Это означает, что при каждом рендеринге компонента будет создаваться новый ключ. Если компоненты рендерятся заново, это может привести к нежелательным эффектам и перерисовкам.

2023-11-06 15:49 UTC, ArslanMustafin commented on src/components/burger-constructor/draggable-element/draggable-element.jsx
> +                handleClose={() => handleDeleteItem(ing)}
**Надо исправить:**

Лучше вынести в отдельную функцию. `ing` ведь доступен не только в `jsx`, но и выше.

2023-11-06 15:49 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    [ingredientsList]);
**Можно лучше:**

т.к. тут 1 зависимость, то можно в 1 `useMemo` это объединить

2023-11-06 15:49 UTC, ArslanMustafin commented on src/services/actions/constructor.js
> +        } else {
**Можно лучше/Рекомендую исправить:**

Булка одна и та же, да и не совсем понимаю зачем ей  дополнительный `идентификатор`.

2023-11-06 15:49 UTC, ArslanMustafin commented on src/services/actions/ingredients.js
> +            })
**Можно лучше:**

```suggestion
            .then(res => {
                dispatch({
                    type: GET_INGREDIENTS_SUCCESS,
                    payload: res.data,
                });
            })
```

2023-11-06 15:49 UTC, ArslanMustafin commented on src/services/reducers/constructorReducer.js
> +        }
**Надо исправить:**

Думаю стоит убрать расчёт цены в компонент `burger-constructor`, она будет использоваться только там, поэтому не нужно её выносить в стор. А также, конструкция case внутри редьюсера должна выполнять только одно действие.

2023-11-06 15:49 UTC, ArslanMustafin commented on src/services/reducers/constructorReducer.js
> +            let updatedConstructorIngredients = [...state.constructorIngredients];
**Надо исправить:**

массивы ссылочный тип данных, поэтому тут нужно использовать `const`, а не `let`

2023-11-06 15:49 UTC, ArslanMustafin commented on src/services/reducers/constructorReducer.js
> +            updatedConstructorIngredients.sort((a, b) => a.orderIndex - b.orderIndex);
**Надо исправить:**

А зачем каждый раз делать сортировку?

2023-11-06 15:49 UTC, ArslanMustafin commented on src/services/reducers/constructorReducer.js
> +            updatedConstructorIngredients.sort((a, b) => a.orderIndex - b.orderIndex);
**Можно лучше:**

старайтесь не мутировать массивы) В js относительно недавно появился вот такой метод: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toSorted. Попробуйте использовать его. Тогда пропадёт необходимость в 55 строчке.

2023-11-06 18:20 UTC, swtormy commented on src/components/burger-constructor/draggable-element/draggable-element.jsx
> +            key={uuidv4()}
хотелось бы подробнее узнать как его правильно использовать.

2023-11-07 05:51 UTC, ArslanMustafin commented on src/components/burger-constructor/draggable-element/draggable-element.jsx
> +            key={uuidv4()}
Про ключи: https://ru.react.js.org/docs/lists-and-keys.html#%D0%9A%D0%BB%D1%8E%D1%87%D0%B8

Если вам нужны уникальные значения для элементов какого-либо массива, то заранее через `mao` добавьте новое поле со значением `uuidv4()`, можно ещё обернуть в `useMemo`, чтобы не было создания массива каждый рендер))

2023-11-07 06:04 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Осталось ещё 1 замечание, которое нужно исправить:**

- <https://disk.yandex.com/i/ePK95Z-Dq0bykw> - Нужно передавать только `_id` ингредиентов;

2023-11-07 06:04 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    const buns = constructorIngredients.filter(ingredient => ingredient.type === 'bun')
**Надо исправить:**

Лучше использовать `find`.
```suggestion
    const bun = constructorIngredients.find(ingredient => ingredient.type === 'bun')
```

2023-11-07 06:04 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    const disabled = constructorIngredients.length === 0 || buns.length !== 2
Тут тоже нужно будеть чуток по другому написать.

```suggestion
    const disabled = constructorIngredients.length === 0 || !bun
```

2023-11-07 06:04 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +      dispatch(createOrder(buns));
**Надо исправить:**

Тут нужно передавть `_id`, а не объекты.

```suggestion
      const ingredientsIds = [bun._id, ...notBuns.map(ingredient => ingredient._id), bun._id];
      dispatch(createOrder(ingredientsIds));
```

2023-11-07 09:03 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-11-07 09:17 UTC, merged