Sprint 5/step 1
swtormy/react-burger pull request #8
Opened 2023-12-27 16:08 UTC by swtormy

2023-12-27 17:35 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;
- Теперь пользователь может посмотреть историю заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- У вас не закрывается сокет соединение, когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. <https://disk.yandex.com/i/oyYf_xLivgUOOw> - это можно проверить в девтулс, во вкладке `networks`.

- При нажатии на кнопку `Оформить заказ` <https://disk.yandex.com/i/YMX4koxAe9CcwA>, Пользователь не переходит на страницу логина, если он не авторизирован.

- <https://disk.yandex.com/i/bJHzGkV4FmIjiQ> - По умолчанию пароля быть не должно;

- Не отображается информация о заказе, если открыть маршрут `profile/orders/:id` в новой вкладке, хотя похожий функционал `/feed/:id` у вас работает корректно.

- <https://disk.yandex.com/i/CeGYZNmm-B-lqw> - При открытии/закрытии модального окна на странице `profile/orders` у вас много раз открывается сокет соединение `/profile/orders`. Сокет должен открываться только 1 раз, при входе на страницу;

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-12-27 17:35 UTC, ArslanMustafin commented on src/components/order-history/order-detail-component.tsx
> +                });
**Можно лучше:**

по хорошему, проверять авторизован пользователь или нет должен компонент `protect-route` и уже там перенаправлять его куда надо.

2023-12-27 17:35 UTC, ArslanMustafin commented on src/components/order-history/order-history.tsx
> +  },[token, dispatch, location])
**Надо исправить:**

Нужно вынести адрес сокета в константу. Константы принято записывать через `UPPER_CASE`.

Здесь не нужна проверка на токен, это должен делать компонент `protect-route`. Если пользователь авторизован, значит токен точно есть, иначе он на эту страницу не попадёт. 

Нужно убрать из зависимостей location

И Нужно добавить закрытие сокета при размонтировании компонента.

```js
  React.useEffect(()=>{
    dispatch(connect(...))
   
    return () => {
     // Закрытие сокета
    }
  },[token, dispatch])
```

2023-12-27 17:35 UTC, ArslanMustafin commented on src/pages/feed-page.tsx
> +    dispatch(connect('wss://norma.nomoreparties.space/orders/all'))
**Надо исправить:**

Нужно вынести адрес сокета в константу. Константы принято записывать через `UPPER_CASE`.

И Нужно добавить закрытие сокета при размонтировании компонента.

```js
  React.useEffect(()=>{
    dispatch(connect(...))
   
    return () => {
     // Закрытие сокета
    }
  },[])
```

2023-12-27 17:35 UTC, ArslanMustafin commented on src/pages/login-page.tsx
> +    console.log("DONE");
**Можно лучше:**

старайтесь не оставлять дебаг-вещи когда отправляете работу на проверку.

2023-12-27 17:35 UTC, ArslanMustafin commented on src/services/middleware/socket-middleware.ts
> +                }
**Вы молодец:**

Классно сделали реконнект сокета по таймеру.

2023-12-27 17:35 UTC, ArslanMustafin commented on src/services/store.ts
> +const webSocketMiddleware = createSocketMiddleware(wsActions)
**Можно лучше:**

Советую сделать отдельные экшены для общих заказов и для заказов пользователя.

```js
const ordersWsActions = {
  wsInit: ORDERS_CONNECTION_INIT,
  wsClose: ORDERS_CONNECTION_CLOSE,
  onOpen: ORDERS_CONNECTION_SUCCESS,
  onClose: ORDERS_CONNECTION_CLOSED,
  onError: ORDERS_CONNECTION_ERROR,
  onMessage: ORDERS_GET_MESSAGE,
};

const feedWsActions = {
  wsInit: FEED_CONNECTION_INIT,
  wsClose: FEED_CONNECTION_CLOSE,
  onOpen: FEED_CONNECTION_SUCCESS,
  onClose: FEED_CONNECTION_CLOSED,
  onError: FEED_CONNECTION_ERROR,
  onMessage: FEED_GET_MESSAGE,
};

const store = createStore(
  rootReducer,
  composeWithDevTools(
    applyMiddleware(
      thunk,
      socketMiddleware(ordersWsActions),
      socketMiddleware(feedWsActions)
    )
  )
);
```

2023-12-28 07:26 UTC, swtormy commented
> ## Code Review
> Здравствуйте!
> 
> Отличная работа.
> 
> ### **Вы молодец!**
> * Сборка и запуск проекта выполняются без ошибок;
> * Реализована страница ленты заказов;
> * Теперь пользователь может посмотреть историю заказов;
> 
> ### **Но есть несколько замечаний, которые нужно исправить:**
> * У вас не закрывается сокет соединение, когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. https://disk.yandex.com/i/oyYf_xLivgUOOw - это можно проверить в девтулс, во вкладке `networks`.
> * При нажатии на кнопку `Оформить заказ` https://disk.yandex.com/i/YMX4koxAe9CcwA, Пользователь не переходит на страницу логина, если он не авторизирован.
> * https://disk.yandex.com/i/bJHzGkV4FmIjiQ - По умолчанию пароля быть не должно;
> * Не отображается информация о заказе, если открыть маршрут `profile/orders/:id` в новой вкладке, хотя похожий функционал `/feed/:id` у вас работает корректно.
> * https://disk.yandex.com/i/CeGYZNmm-B-lqw - При открытии/закрытии модального окна на странице `profile/orders` у вас много раз открывается сокет соединение `/profile/orders`. Сокет должен открываться только 1 раз, при входе на страницу;
> * Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);
> 
> ### **Сделает код лучше:**
> * Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders
> 
> ### **_Подробно эти и более мелкие замечания, отмечены в коде._**
> ### **После исправления всех замечаний, работа будет принята)**

Добрый день! спасибо за ревью! в голове не укладывается, как забыл токен в /orders запихнуть))

Есть не понимание по некоторым пунктам:
При нажатии на кнопку Оформить заказ https://disk.yandex.com/i/YMX4koxAe9CcwA, Пользователь не переходит на страницу логина, если он не авторизирован.  - это странно, у меня переходит https://disk.yandex.com/i/CtpWPJ7mteWh0Q. вот код - https://disk.yandex.com/i/IQea_S9Yv9tBrA.

https://disk.yandex.com/i/bJHzGkV4FmIjiQ - По умолчанию пароля быть не должно; - в макетах есть звездочки https://disk.yandex.com/i/tqz43SDtkIjQ5Q. поэтому по умолчанию добавляются звездочки https://disk.yandex.com/i/L7sgx8d66koYuA. не помню чтобы в тз было написано, что по умолчанию нужно иметь пустое поле и не обращать внимания на звездочки в макете.

Не отображается информация о заказе, если открыть маршрут profile/orders/:id в новой вкладке, хотя похожий функционал /feed/:id у вас работает корректно. - у меня отображается, как в модальном окне - https://disk.yandex.com/i/L_2bg4fGK7RVYg так и в качестве страницы - https://disk.yandex.com/i/sd81Mp8AFq77qg.

2023-12-28 16:01 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-12-28 16:01 UTC, ArslanMustafin commented on src/services/store.ts
> +const webSocketMiddlewareFeed = createSocketMiddleware(feedWsActions)
**Рекомендую исправить:**

сейчас у вас открытие сокета происходит 2 раза, а должно быть 1. Это происходит из-за того, что вы не создали для каждого сокета свои экшены)) 2-ой сокет подхватывает  WSConnect и тоже открывает соединение с тем же url.

Вот тут показал пример: https://github.com/swtormy/react-burger/pull/8#discussion_r1437171078

2023-12-28 16:09 UTC, ArslanMustafin commented
> > ## Code Review
> > Здравствуйте!
> > Отличная работа.
> > ### **Вы молодец!**
> > 
> > * Сборка и запуск проекта выполняются без ошибок;
> > * Реализована страница ленты заказов;
> > * Теперь пользователь может посмотреть историю заказов;
> > 
> > ### **Но есть несколько замечаний, которые нужно исправить:**
> > 
> > * У вас не закрывается сокет соединение, когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. https://disk.yandex.com/i/oyYf_xLivgUOOw - это можно проверить в девтулс, во вкладке `networks`.
> > * При нажатии на кнопку `Оформить заказ` https://disk.yandex.com/i/YMX4koxAe9CcwA, Пользователь не переходит на страницу логина, если он не авторизирован.
> > * https://disk.yandex.com/i/bJHzGkV4FmIjiQ - По умолчанию пароля быть не должно;
> > * Не отображается информация о заказе, если открыть маршрут `profile/orders/:id` в новой вкладке, хотя похожий функционал `/feed/:id` у вас работает корректно.
> > * https://disk.yandex.com/i/CeGYZNmm-B-lqw - При открытии/закрытии модального окна на странице `profile/orders` у вас много раз открывается сокет соединение `/profile/orders`. Сокет должен открываться только 1 раз, при входе на страницу;
> > * Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);
> > 
> > ### **Сделает код лучше:**
> > 
> > * Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders
> > 
> > ### **_Подробно эти и более мелкие замечания, отмечены в коде._**
> > ### **После исправления всех замечаний, работа будет принята)**
> 
> Добрый день! спасибо за ревью! в голове не укладывается, как забыл токен в /orders запихнуть))
> 
> Есть не понимание по некоторым пунктам: При нажатии на кнопку Оформить заказ https://disk.yandex.com/i/YMX4koxAe9CcwA, Пользователь не переходит на страницу логина, если он не авторизирован. - это странно, у меня переходит https://disk.yandex.com/i/CtpWPJ7mteWh0Q. вот код - https://disk.yandex.com/i/IQea_S9Yv9tBrA.
> 
> https://disk.yandex.com/i/bJHzGkV4FmIjiQ - По умолчанию пароля быть не должно; - в макетах есть звездочки https://disk.yandex.com/i/tqz43SDtkIjQ5Q. поэтому по умолчанию добавляются звездочки https://disk.yandex.com/i/L7sgx8d66koYuA. не помню чтобы в тз было написано, что по умолчанию нужно иметь пустое поле и не обращать внимания на звездочки в макете.
> 
> Не отображается информация о заказе, если открыть маршрут profile/orders/:id в новой вкладке, хотя похожий функционал /feed/:id у вас работает корректно. - у меня отображается, как в модальном окне - https://disk.yandex.com/i/L_2bg4fGK7RVYg так и в качестве страницы - https://disk.yandex.com/i/sd81Mp8AFq77qg.

1) Действительно, сейчас при нажатии на кнопку оформить заказ всё работает корректно, могу предположить что тогда были какие-то проблемы с куками, допустим токен был, но он был не валидный или ещё что-то. Из-за большого количества проверок там могло что-то перетереться)) Даже если бы проблема осталась, я бы локализовл её у себя, и написал об этом в комментарии)) 
2) По поводу пароля, спорное утверждение. По макету видно, что звёздочки там стоят не по умолчанию, а их вводит пользователь https://disk.yandex.com/i/Xxt45i1e0GiHiQ. Дизайнер скорее всего просто забыл убрать это, когда копировал поле https://disk.yandex.com/i/PPF7xT381g4CTA. 
3) Тут я чуток ошибся, и не убрал эту запись после проверки данного функционала)) прошу прощения!.

2024-01-15 17:23 UTC, merged